---
title: "Data visualization"
author: "Jillian Allison"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# General use packages:
library(tidyverse)
library(here)
library(janitor)

# Specifically for plots:
library(patchwork)
library(ggrepel)
library(gghighlight)
library(paletteer)
library(ggExtra)
library(ggbeeswarm)

# And for another dataset we'll explore:
library(gapminder)

# Spatial
# library(sf)
```

### Read in lizard data 
```{r}
lizards <- read_csv(here("data_tidy","lizards.csv"))
```

```{r}
ggplot(data = lizards,
       aes(x = total_length, 
           y = weight)) + 
  geom_point() 
  
```

### Create a histogram of total lengths for all lizards in the data set
```{r}
ggplot(data = lizards, 
       aes(x = total_length)) + 
  geom_histogram(bins = 20, 
                 color = "orange", 
                 fill = "purple", 
                 size = 0.2, 
                 linetype = "dotted") 
# IF YOU ARENT CHANGING AN AESTHETIC MAPPED ON A VARIABLE, IT SHOULD NOT BE IN AES 
```

```{r}
ggplot(data = lizards, 
       aes(x = total_length,
           y = weight)) + 
  geom_point(
    shape = 22,
    color = "cyan4",
    fill = "yellow", 
    size = 4, 
    alpha = 0.4 # transparency 
  )
```

```{r}
ggplot(data = lizards, 
       aes(x = total_length,
           y = weight)) + 
  geom_point(aes(color = common_name, 
                 size = total_length),
             alpha = 0.5) + 
  theme_minimal() 
```

```{r}
ggplot(data = lizards, 
       aes(x = total_length,
           y = weight)) + 
  geom_point(aes(color = common_name)) + 
  facet_wrap(~common_name) + 
  theme_minimal() 
```

```{r}
lizard_total_counts_gbsum <- lizards %>% 
  group_by(common_name) %>%
  summarize(total_count = n())

lizard_total_counts_dplyr <- lizards %>%
  count(common_name)
```

```{r}
ggplot(data = lizard_total_counts_gbsum, 
       aes(y = fct_reorder(common_name, -total_count), 
           x = total_count)) + 
  geom_col() 
```

Create scatterplots, faceted by species common name, for total length versus weight. The color and shape of points should differ based on the species common name. Change the theme. Make each faceted panel have flexible axis limits. (scales should be free) 

```{r}
ggplot(data = lizards, 
       aes(x = total_length,
           y = weight)) + 
  geom_point(aes(color = common_name, 
                 shape = common_name)) + 
  facet_wrap(~common_name, 
             scales = "free") +
  theme_minimal()
```

